name: Pytest

on:
  pull_request:
    types: [opened, reopened,  synchronize]
  push:
    branches:
      - main

jobs:
  run_pytest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: |
            dev-requirements.txt
            setup.py

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r dev-requirements.txt

      - name: Test with pytest
        run: |
          pytest
